services:
  tomee:
    image: tomee:jre17-webprofile
    container_name: tomee
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomee/webapps
      - scss:/usr/local/tomee/webapps/JavaWeb/assets/scss
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
      MYSQL_USER: pere
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

  java-style:
    container_name: style
    image: node:20
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ../StyleJava/vite:/app
      - scss:/app/tomee
    ports:
      - "8082:5173"


volumes:
  db_data:
  scss: